### ISSUE TITLE
checking for gender when giving epithet in russian

### ISSUE THREAD

**Issue by SuperProCoolName** [Kizder/CK3_Mods#11]
so in russian we need separate "epithets" for each gender, like the Brave is Храбр**ЫЙ** (for male) and Храбр**АЯ** (for female)
can we do something about it?

**Comment by Kizder** [comment]
Sorry but I don't have any skill in russian so there is no russian translation.
But otherwise yes it's possible to have different gender depending on gender, it's implemented for french.
