### ISSUE TITLE
Bug with Nickname Black Widow

### ISSUE THREAD

**Issue by NicolasGrosjean** [Kizder/CK3_Mods#7]
The error log indicates an issue in event epithet.0264 which gives the Black Widow nickname.

`Script location: file: events/epithet_events.txt line: 5168`

In the code we see `scope:spouse` which seems wrong because spouse was not saved in the scope (`save_scope_as = spouse`).

You should use `any_spouse` if it works for dead spouses.

**Comment by Kizder** [comment]
Thanks for the update.
Sorry it tooks me a long time to see it and correct it. It will be corrected in the next patch.
